version: "3"

services:
  proxy:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      HOST: "${HOST}"
      HOST_PORT: 8080
      ADMIN_PORT: 9091
      LISTENER_PORT: 9090
    ports:
      # proxy
      - 9090:9090
      # admin site
      - 9091:9091

